Implement Like Button Toggle Feature in Blog Component
Open-Code-Crafters/FitFlex pull request #197
Opened 2024-10-12 08:05 UTC by harshucoder

# Title and Issue number 

Title : Implement Like Button Toggle Feature in Blog Component

Issue No. : #175

Code Stack : React.js, JavaScript, CSS

Close #175

# Video (mandatory)

https://github.com/user-attachments/assets/d9c16e7c-812d-49b0-b7c8-f7f60d6e384f

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have gone through the `contributing.md` file before contributing.

**Additional context (Mandatory)**

***Are you contributing under any Open-source programme?***

- [x] I'm a GSSOC-EXT contributor
- [x] I'm a HACKTOBERFEST contributor

2024-10-12 19:08 UTC, jeevan10017 requested changes
remove pakage-lock.json

2024-10-13 03:23 UTC, harshucoder commented
@jeevan10017 i have made the requested changes.

2024-10-14 04:28 UTC, harshucoder commented
@jeevan10017 plz do merge the pr

2024-10-14 06:30 UTC, jeevan10017 approved these changes

2024-10-14 06:31 UTC, merged