Update Pages Alignment
Open-Code-Crafters/FitFlex pull request #327
Opened 2024-10-24 09:59 UTC by Rajput-xv

# Title and Issue number 
Title : Updated pages alignment

Issue No. : #316

Code Stack : 

Close #316 

@GAVINESHWAR  kindly have a look & add the respective label to PR.

# Video (mandatory)

https://github.com/user-attachments/assets/4ef19d92-9ba9-4fd1-b4c9-013d60fd2a6a

# Checklist:

- [ X] I have mentioned the issue number in my Pull Request.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md` if its a new page/tech stack
- [ X] I have gone through the  `contributing.md` file before contributing

**Additional context (Mandatory )**

***Are you contributing under any Open-source programme?***

- [ X] I'm a GSSOC-EXT contributor
- [ X] I'm a HACKTOBERFEST contributor

2024-10-25 20:46 UTC, jeevan10017 approved these changes

2024-10-25 20:49 UTC, jeevan10017 requested changes
@Rajput-xv resolve conflicts

2024-10-27 09:40 UTC, Rajput-xv commented
> @Rajput-xv resolve conflicts

@jeevan10017 
kindly check!

2024-10-29 18:26 UTC, Rajput-xv commented
@jeevan10017 
Kindly look into this.

2024-10-31 02:26 UTC, merged